// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v3.19.1
// source: interview.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { CallContext, CallOptions } from "nice-grpc-common";

export const protobufPackage = "interview";

export interface NextQuestionRequest {
  attemptId: number;
  userId: number;
}

export interface QuestionChunk {
  textDelta?:
    | string
    | undefined;
  /** Полные данные (ID, тип) в конце стрима */
  finalData?: QuestionData | undefined;
}

export interface QuestionData {
  questionId: number;
  fullText: string;
  complexity: number;
}

export interface ErrorResponse {
  message: string;
  code: number;
}

function createBaseNextQuestionRequest(): NextQuestionRequest {
  return { attemptId: 0, userId: 0 };
}

export const NextQuestionRequest: MessageFns<NextQuestionRequest> = {
  encode(message: NextQuestionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.attemptId !== 0) {
      writer.uint32(8).int64(message.attemptId);
    }
    if (message.userId !== 0) {
      writer.uint32(16).int64(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NextQuestionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNextQuestionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.attemptId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<NextQuestionRequest>): NextQuestionRequest {
    return NextQuestionRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<NextQuestionRequest>): NextQuestionRequest {
    const message = createBaseNextQuestionRequest();
    message.attemptId = object.attemptId ?? 0;
    message.userId = object.userId ?? 0;
    return message;
  },
};

function createBaseQuestionChunk(): QuestionChunk {
  return { textDelta: undefined, finalData: undefined };
}

export const QuestionChunk: MessageFns<QuestionChunk> = {
  encode(message: QuestionChunk, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.textDelta !== undefined) {
      writer.uint32(10).string(message.textDelta);
    }
    if (message.finalData !== undefined) {
      QuestionData.encode(message.finalData, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuestionChunk {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuestionChunk();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.textDelta = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.finalData = QuestionData.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<QuestionChunk>): QuestionChunk {
    return QuestionChunk.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QuestionChunk>): QuestionChunk {
    const message = createBaseQuestionChunk();
    message.textDelta = object.textDelta ?? undefined;
    message.finalData = (object.finalData !== undefined && object.finalData !== null)
      ? QuestionData.fromPartial(object.finalData)
      : undefined;
    return message;
  },
};

function createBaseQuestionData(): QuestionData {
  return { questionId: 0, fullText: "", complexity: 0 };
}

export const QuestionData: MessageFns<QuestionData> = {
  encode(message: QuestionData, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.questionId !== 0) {
      writer.uint32(8).int64(message.questionId);
    }
    if (message.fullText !== "") {
      writer.uint32(18).string(message.fullText);
    }
    if (message.complexity !== 0) {
      writer.uint32(24).int32(message.complexity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuestionData {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuestionData();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.questionId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fullText = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.complexity = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<QuestionData>): QuestionData {
    return QuestionData.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<QuestionData>): QuestionData {
    const message = createBaseQuestionData();
    message.questionId = object.questionId ?? 0;
    message.fullText = object.fullText ?? "";
    message.complexity = object.complexity ?? 0;
    return message;
  },
};

function createBaseErrorResponse(): ErrorResponse {
  return { message: "", code: 0 };
}

export const ErrorResponse: MessageFns<ErrorResponse> = {
  encode(message: ErrorResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.message !== "") {
      writer.uint32(10).string(message.message);
    }
    if (message.code !== 0) {
      writer.uint32(16).int32(message.code);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ErrorResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseErrorResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.code = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  create(base?: DeepPartial<ErrorResponse>): ErrorResponse {
    return ErrorResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ErrorResponse>): ErrorResponse {
    const message = createBaseErrorResponse();
    message.message = object.message ?? "";
    message.code = object.code ?? 0;
    return message;
  },
};

export type QuestionStreamServiceDefinition = typeof QuestionStreamServiceDefinition;
export const QuestionStreamServiceDefinition = {
  name: "QuestionStreamService",
  fullName: "interview.QuestionStreamService",
  methods: {
    /**
     * Стрим для получения вопроса.
     * Фронтенд отправляет ID попытки, бэкенд начинает передавать токены текста.
     */
    streamNextQuestion: {
      name: "StreamNextQuestion",
      requestType: NextQuestionRequest as typeof NextQuestionRequest,
      requestStream: false,
      responseType: QuestionChunk as typeof QuestionChunk,
      responseStream: true,
      options: {},
    },
  },
} as const;

export interface QuestionStreamServiceImplementation<CallContextExt = {}> {
  /**
   * Стрим для получения вопроса.
   * Фронтенд отправляет ID попытки, бэкенд начинает передавать токены текста.
   */
  streamNextQuestion(
    request: NextQuestionRequest,
    context: CallContext & CallContextExt,
  ): ServerStreamingMethodResult<DeepPartial<QuestionChunk>>;
}

export interface QuestionStreamServiceClient<CallOptionsExt = {}> {
  /**
   * Стрим для получения вопроса.
   * Фронтенд отправляет ID попытки, бэкенд начинает передавать токены текста.
   */
  streamNextQuestion(
    request: DeepPartial<NextQuestionRequest>,
    options?: CallOptions & CallOptionsExt,
  ): AsyncIterable<QuestionChunk>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

export type ServerStreamingMethodResult<Response> = { [Symbol.asyncIterator](): AsyncIterator<Response, void> };

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
